[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rust-project-template"
version = "1.0.0"
description = "A template repository for Rust projects."
requires-python = ">=3.12"

dependencies = [
    "jinja2",
    "click",
]

[project.scripts]
create-project = "rust_project_template.__main__:main"

